# This file was generated by GoReleaser. DO NOT EDIT.
cask "apkg" do
  name "apkg"
  desc "A package manager for coding agent skills, MCP servers, and subagents"
  homepage "https://github.com/agentpkg/apkg"
  version "0.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apkg"

  on_macos do
    on_intel do
      url "https://github.com/agentpkg/apkg/releases/download/v#{version}/apkg-darwin-amd64.zip",
        verified: "github.com/agentpkg/apkg"
      sha256 "c5506eaaf44bdeccb2c59d406ac790363197866a71b300da0a356ade3ada90e7"
    end
    on_arm do
      url "https://github.com/agentpkg/apkg/releases/download/v#{version}/apkg-darwin-arm64.zip",
        verified: "github.com/agentpkg/apkg"
      sha256 "01057c24d53c98b895f715a8704ce45180f9eddf5d583e26ed5419d444ca4572"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/agentpkg/apkg/releases/download/v#{version}/apkg-linux-amd64.zip",
        verified: "github.com/agentpkg/apkg"
      sha256 "d883232ae16dd64270213cc1607567b3cb2a76164439643b5d14f48e10df4282"
    end
    on_arm do
      url "https://github.com/agentpkg/apkg/releases/download/v#{version}/apkg-linux-arm64.zip",
        verified: "github.com/agentpkg/apkg"
      sha256 "803edbfdce496a080e5c924bc07b7d0b330ff6936f7ec73dcc965372cdd67880"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/apkg"]
    end
  end

  # No zap stanza required
end
