# This file was generated by GoReleaser. DO NOT EDIT.
cask "apkg" do
  name "apkg"
  desc "A package manager for coding agent skills, MCP servers, and subagents"
  homepage "https://github.com/agentpkg/apkg"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apkg"

  on_macos do
    on_intel do
      url "https://github.com/agentpkg/apkg/releases/download/v#{version}/apkg-darwin-amd64.zip",
        verified: "github.com/agentpkg/apkg"
      sha256 "435d689b7828535c7748a3972bd92e0c554be03f4c062e988438b1c982e3476b"
    end
    on_arm do
      url "https://github.com/agentpkg/apkg/releases/download/v#{version}/apkg-darwin-arm64.zip",
        verified: "github.com/agentpkg/apkg"
      sha256 "84f00b24e4fdfe6c2ce57d6f067fe0bd2c0aeff179c6b85574a70bfc770b0984"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/agentpkg/apkg/releases/download/v#{version}/apkg-linux-amd64.zip",
        verified: "github.com/agentpkg/apkg"
      sha256 "f238417b4c5f28d4e4eb75bbd11f90a1f1ae54b14a11bca0f2a9e172ec6dda12"
    end
    on_arm do
      url "https://github.com/agentpkg/apkg/releases/download/v#{version}/apkg-linux-arm64.zip",
        verified: "github.com/agentpkg/apkg"
      sha256 "a92bf3cae0a7440885aef5ae7119091403284a0cb21551e7f47335821ac206b2"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/apkg"]
    end
  end

  # No zap stanza required
end
