# This file was generated by GoReleaser. DO NOT EDIT.
cask "apkg" do
  name "apkg"
  desc "A package manager for coding agent skills, MCP servers, and subagents"
  homepage "https://github.com/agentpkg/apkg"
  version "0.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "apkg"

  on_macos do
    on_intel do
      url "https://github.com/agentpkg/apkg/releases/download/v#{version}/apkg-darwin-amd64.zip",
        verified: "github.com/agentpkg/apkg"
      sha256 "0b92f486e740b15e9f310b94fdcc9c3bf6805fcd921334f8483f68b8fb213f11"
    end
    on_arm do
      url "https://github.com/agentpkg/apkg/releases/download/v#{version}/apkg-darwin-arm64.zip",
        verified: "github.com/agentpkg/apkg"
      sha256 "fdcb961e2a099013151b469611c0d9d13949d666648382d7e7982ecd26f3b2ce"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/agentpkg/apkg/releases/download/v#{version}/apkg-linux-amd64.zip",
        verified: "github.com/agentpkg/apkg"
      sha256 "8836398631d9204dd5edac1fac9f129f2eebd446276cdfee62cbd4de9b27de2d"
    end
    on_arm do
      url "https://github.com/agentpkg/apkg/releases/download/v#{version}/apkg-linux-arm64.zip",
        verified: "github.com/agentpkg/apkg"
      sha256 "032564c00f8b70b6bee5c7a5c9fd2d6e130b06d5cad01afa27e3cd7fa58c3fd1"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/apkg"]
    end
  end

  # No zap stanza required
end
